/**
 *
 *  DevicesController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "ControllerBase.h"
#include <facades/DevicesFacade.h>

using namespace drogon;
/**
 * @brief this class is created by the drogon_ctl command (drogon_ctl create controller -r DevicesController).
 * this class is a restful API controller.
 */
class DevicesController:
    public ControllerBase<facade::DevicesFacade>,
    public drogon::HttpController<DevicesController>
{
  public:
    METHOD_LIST_BEGIN
    // use METHOD_ADD to add your custom processing function here;
    METHOD_ADD(DevicesController::getOne,"/{1}",Get,Options);
    METHOD_ADD(DevicesController::get,"",Get,Options);
    METHOD_ADD(DevicesController::create,"",Post,Options);
    METHOD_ADD(DevicesController::updateOne,"/{1}",Put,Options);
    //METHOD_ADD(DevicesController::update,"",Put,Options);
    METHOD_ADD(DevicesController::deleteOne,"/{1}",Delete,Options);
    METHOD_LIST_END

    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                std::string &&id);
    void updateOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                std::string &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   std::string &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback);

//    void update(const HttpRequestPtr &req,
//                std::function<void(const HttpResponsePtr &)> &&callback);

};
