/**
 *
 *  DevicesController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "ControllerBase.h"
#include <facades/DevicesFacade.h>
#include <models/orm_model/Devices.h>
#include <models/request_model/DevicesRequest.h>
#include <controllers/exceptionWrapper/TryNumberParsing.h>
#include <controllers/exceptionWrapper/TryFacadeCall.h>
#include <controllers/responses/Response.h>
#include <filters/FilterAliases.h>

using namespace drogon;
/**
 * @brief this class is created by the drogon_ctl command (drogon_ctl create controller -r DevicesController).
 * this class is a restful API controller.
 */
class DevicesController:
    public ControllerBase<facade::DevicesFacade>,
    public drogon::HttpController<DevicesController>
{
    using Devices = drogon_model::defaultdb::Devices;
    using DevicesList = list_model::DevicesList;
    using DevicesRequest = request_model::DevicesRequest;
  public:
    METHOD_LIST_BEGIN
    // use METHOD_ADD to add your custom processing function here;
        ADD_METHOD_TO(DevicesController::getOne,"device/{1}",Get,Options);
    ADD_METHOD_TO(DevicesController::get,"device",Get,Options);
    ADD_METHOD_TO(DevicesController::create,"device",Post,Options, LoginFilter);
    //METHOD_ADD(DevicesController::update,"",Put,Options);
    ADD_METHOD_TO(DevicesController::deleteOne,"device/{1}",Delete,Options, OwnerFilter);
    METHOD_LIST_END

        Task<HttpResponsePtr> getOne(const HttpRequestPtr req, const std::string &id);
    Task<HttpResponsePtr> deleteOne(const HttpRequestPtr req, const std::string &id);
    Task<HttpResponsePtr> get(const HttpRequestPtr req);
    Task<HttpResponsePtr> create(const HttpRequestPtr req);

//    void update(const HttpRequestPtr &req,
//                std::function<void(const HttpResponsePtr &)> &&callback);

};
