/**
 *
 *  DevicesController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "DevicesController.h"
#include <string>


void DevicesController::getOne(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback,
                               std::string &&id)
{
}

void DevicesController::get(const HttpRequestPtr &req,
                            std::function<void(const HttpResponsePtr &)> &&callback)
{
}
void DevicesController::create(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback)
{
}
void DevicesController::updateOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  std::string &&id)
{
}

/*
void DevicesController::update(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback)
{

}*/

void DevicesController::deleteOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  std::string &&id)
{
}
