/**
 *
 *  FireportDeviceController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "ControllerBase.h"
#include <facades/FireportDeviceDataFacade.h>
#include <models/request_model/FireportDeviceDataRequest.h>
#include <models/filter_model/FireportDeviceFilter.h>
#include <filters/FilterAliases.h>
#include <controllers/exceptionWrapper/TryFacadeCall.h>
#include <controllers/exceptionWrapper/TryNumberParsing.h>


using namespace drogon;
using namespace filter_model;
/**
 * @brief this class is created by the drogon_ctl command (drogon_ctl create controller -r FireportDeviceController).
 * this class is a restful API controller.
 */
class FireportDeviceController :
	public ControllerBase<facade::FireportDeviceDataFacade>,
	public drogon::HttpController<FireportDeviceController>
{
public:
	METHOD_LIST_BEGIN
		// use METHOD_ADD to add your custom processing function here;
		ADD_METHOD_TO(FireportDeviceController::getOne, "fireport/{1}", Get, LoginFilter);
	ADD_METHOD_TO(FireportDeviceController::getAll, "fireport/all", Get, AdminFilter);
	ADD_METHOD_TO(FireportDeviceController::getAllOwner, "fireport", Get, LoginFilter);
	ADD_METHOD_TO(FireportDeviceController::getFilterOwner, "fireport/filter", Post, LoginFilter);
	ADD_METHOD_TO(FireportDeviceController::getFilterAll, "fireport/filter/all", Post, AdminFilter);
	ADD_METHOD_TO(FireportDeviceController::create, "fireport", Post, OwnerFilter);
	ADD_METHOD_TO(FireportDeviceController::updateOne, "fireport", Put, OwnerFilter);
	ADD_METHOD_TO(FireportDeviceController::deleteOne, "fireport/{1}", Delete, OwnerFilter);
	//ADD_METHOD_TO(FireportDeviceController::notifyDeviceById, "fireport/notify/{1}", Post, LoginFilter);
	//ADD_METHOD_TO(FireportDeviceController::notifyDeviceAllOwner, "fireport/notify", Post, OwnerFilter);
	//ADD_METHOD_TO(FireportDeviceController::notifyDeviceAll, "fireport/notify/all", Post, AdminFilter);
	METHOD_LIST_END

		Task<HttpResponsePtr> getOne(const HttpRequestPtr req, const std::string& id);
	Task<HttpResponsePtr> getFilterOwner(const HttpRequestPtr req, const FireportDeviceFilter& filter);
	Task<HttpResponsePtr> getFilterAll(const HttpRequestPtr req, const FireportDeviceFilter& filter);
	Task<HttpResponsePtr> getAllOwner(const HttpRequestPtr req);
	Task<HttpResponsePtr> getAll(const HttpRequestPtr req);
	Task<HttpResponsePtr> updateOne(const HttpRequestPtr req, const request_model::FireportDeviceDataRequest& model);
	Task<HttpResponsePtr> deleteOne(const HttpRequestPtr req, const std::string& id);
	Task<HttpResponsePtr> create(const HttpRequestPtr req, const request_model::FireportDeviceDataRequest& model);
	//Task<HttpResponsePtr> notifyDeviceById(const HttpRequestPtr& req, const std::string& id);
	//Task<HttpResponsePtr> notifyDeviceAllOwner(const HttpRequestPtr& req);
	//Task<HttpResponsePtr> notifyDeviceAll(const HttpRequestPtr& req);
//    void update(const HttpRequestPtr &req,
//                std::function<void(const HttpResponsePtr &)> &&callback);

};
