/**
 *
 *  SensorData.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include "ControllerBase.h"
#include <drogon/HttpController.h>
#include <models/SensorData.h>
#include <request/SensorDataRequest.h>
#include <facades/SensorDataFacade.h>
#include <drogon/orm/CoroMapper.h>
#include <controllers/exceptionWrapper/TryNumberParsing.h>
#include <controllers/exceptionWrapper/TryFacadeCall.h>


using namespace drogon;
/**
 * @brief this class is created by the drogon_ctl command (drogon_ctl create controller -r SensorData --resource=../models).
 * this class is a restful API controller.
 */
class SensorData :
	public ControllerBase<facade::SensorDataFacade>,
	public drogon::HttpController<SensorData>
{
public:
	METHOD_LIST_BEGIN
		// use METHOD_ADD to add your custom processing function here;
		METHOD_ADD(SensorData::getById, "/get/{1}", Get);
	METHOD_ADD(SensorData::get, "/get", Get);
	METHOD_ADD(SensorData::updateOne, "/update", Put);
	METHOD_ADD(SensorData::deleteOne, "/delete/{1}", Delete);
	METHOD_ADD(SensorData::create, "/create", Post);
	//ADD_METHOD_TO(SensorData::update,"../models",Put,Options);
	METHOD_LIST_END

		Task<HttpResponsePtr> getById(const HttpRequestPtr req, const std::string& id);
	Task<HttpResponsePtr> get(const HttpRequestPtr req);
	Task<HttpResponsePtr> updateOne(const HttpRequestPtr req, const request_model::SensorData& data);
	Task<HttpResponsePtr> deleteOne(const HttpRequestPtr req, const std::string& id);
	Task<HttpResponsePtr> create(const HttpRequestPtr req, const request_model::SensorData& data);
};
