/**
 *
 *  SensorData.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once


#include <models/SensorData.h>
#include <request/SensorDataRequest.h>
#include <drogon/HttpController.h>
#include <controllers/callbacks/SensorDataCallback.h>

using namespace drogon;
/**
 * @brief this class is created by the drogon_ctl command (drogon_ctl create controller -r SensorData --resource=../models).
 * this class is a restful API controller.
 */
class SensorData : public drogon::HttpController<SensorData>, public callbacks::SensorDataCallback
{
public:
	METHOD_LIST_BEGIN
		// use METHOD_ADD to add your custom processing function here;
		METHOD_ADD(SensorData::getOne, "/get?id={1}", Get);
	METHOD_ADD(SensorData::get, "/get", Get);
	METHOD_ADD(SensorData::updateOne, "/update", Put);
	METHOD_ADD(SensorData::deleteOne, "/delete?id={1}", Delete);
	METHOD_ADD(SensorData::create, "/create", Post);
	//ADD_METHOD_TO(SensorData::update,"../models",Put,Options);
	METHOD_LIST_END

		void getOne(const HttpRequestPtr& req,
			std::function<void(const HttpResponsePtr&)>&& callback,
			const std::string& id);
	void updateOne(const HttpRequestPtr& req,
		std::function<void(const HttpResponsePtr&)>&& callback,
		request_model::SensorData&& data);
	void deleteOne(const HttpRequestPtr& req,
		std::function<void(const HttpResponsePtr&)>&& callback,
		std::string&& id);
	void get(const HttpRequestPtr& req,
		std::function<void(const HttpResponsePtr&)>&& callback);
	void create(const HttpRequestPtr& req,
		std::function<void(const HttpResponsePtr&)>&& callback,
		request_model::SensorData&& data);

};
