/**
 *
 *  UsersController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "ControllerBase.h"
#include <facades/UsersFacade.h>

using namespace drogon;
/**
 * @brief this class is created by the drogon_ctl command (drogon_ctl create controller -r UsersController).
 * this class is a restful API controller.
 */
class UsersController:
    public ControllerBase<facade::UsersFacade>,
    public drogon::HttpController<UsersController>
{
  public:
    METHOD_LIST_BEGIN
    // use METHOD_ADD to add your custom processing function here;
    METHOD_ADD(UsersController::getOne,"/{1}",Get,Options);
    METHOD_ADD(UsersController::get,"",Get,Options);
    METHOD_ADD(UsersController::create,"",Post,Options);
    METHOD_ADD(UsersController::updateOne,"/{1}",Put,Options);
    //METHOD_ADD(UsersController::update,"",Put,Options);
    METHOD_ADD(UsersController::deleteOne,"/{1}",Delete,Options);
    METHOD_LIST_END

    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                std::string &&id);
    void updateOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                std::string &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   std::string &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback);

//    void update(const HttpRequestPtr &req,
//                std::function<void(const HttpResponsePtr &)> &&callback);

};
