/**
 *
 *  UsersController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <facades/UsersFacade.h>
#include <models/auth_model/AuthModel.h>
#include "ControllerBase.h"
#include <drogon/HttpController.h>
#include <models/request_model/UsersRequest.h>
#include <controllers/exceptionWrapper/TryNumberParsing.h>
#include <controllers/exceptionWrapper/TryFacadeCall.h>
#include <controllers/responses/Response.h>
#include <filters/FilterAliases.h>

using namespace drogon;
/**
 * @brief this class is created by the drogon_ctl command (drogon_ctl create controller -r UsersController).
 * this class is a restful API controller.
 */
class UsersController :
	public ControllerBase<facade::UsersFacade>,
	public drogon::HttpController<UsersController>
{
	using AuthModel = auth_model::AuthModel;
	using UsersRequest = request_model::UsersRequest;
	using Users = drogon_model::defaultdb::Users;
	using UsersList = list_model::UsersList;

public:
	METHOD_LIST_BEGIN
		// use METHOD_ADD to add your custom processing function here;
		ADD_METHOD_TO(UsersController::getOne, "user/{1}", Get, Options);
	ADD_METHOD_TO(UsersController::get, "user", Get, Options);
	ADD_METHOD_TO(UsersController::signUp, "auth", Post, Options);
	ADD_METHOD_TO(UsersController::signIn, "auth", Get, Options);
	ADD_METHOD_TO(UsersController::deleteOne, "user/{1}", Delete, Options, OwnerFilter);
	METHOD_LIST_END

		Task<HttpResponsePtr> getOne(const HttpRequestPtr req, const std::string& idStr);
	Task<HttpResponsePtr> get(const HttpRequestPtr req);
	Task<HttpResponsePtr> deleteOne(const HttpRequestPtr req, const std::string& id);
	Task<HttpResponsePtr> signUp(const HttpRequestPtr req);
	Task<HttpResponsePtr> signIn(const HttpRequestPtr req);

	//    void update(const HttpRequestPtr &req,
	//                std::function<void(const HttpResponsePtr &)> &&callback);

};
